### PR TITLE
Track upstream

### PR DESCRIPTION
**Pull request by HSorensen**

### CODE REVIEW

**Comment by HSorensen** [comment]
@SamuraiCrow please approve. This is just a sync with upstream

**Comment by SamuraiCrow** [comment]
Done!

**Review by cooljeanius — APPROVED** [review]

**Comment by HSorensen** [comment]
@SamuraiCrow can you add your reviewed by?

**Review by SamuraiCrow — APPROVED** [review]

**Comment by SamuraiCrow** [comment]
Head branch is out of date but feel free to merge.

**Pull request closed without merging**
